# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sanntis_dev',
                'doc_host': 'https://SantiagoSanchezF.github.io',
                'git_url': 'https://github.com/SantiagoSanchezF/sanntis_dev',
                'lib_path': 'sanntis_dev'},
  'syms': {'sanntis_dev.core': {'sanntis_dev.core.foo': ('core.html#foo', 'sanntis_dev/core.py')}}}